/*
 *   Copyright 2013 Ant Kutschera
 *   
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
USE SCALABOOK_APP;

DROP VIEW IF EXISTS BOOKINGS;

DROP TABLE IF EXISTS SESSION_CACHE;
DROP TABLE IF EXISTS CONFIG;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS ACCOUNT_ENTRY;
DROP TABLE IF EXISTS ORDER_ITEM;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS RATING_USER_MAPPING;
DROP TABLE IF EXISTS RATING;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS EVENTS_SEQUENCES;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER_SEQUENCE;
DROP TABLE IF EXISTS RULE;
DROP TABLE IF EXISTS RULE_SEQUENCE;

-- ---------------------------------------------------------------
-- USER MANAGEMENT
-- ---------------------------------------------------------------
CREATE TABLE USER (
	ID BIGINT NOT NULL, 
	EMAIL VARCHAR(255) UNIQUE NOT NULL, 
	PASSWORD VARCHAR(255) NOT NULL, 
	NAME VARCHAR(255) NOT NULL, 
	PRIMARY KEY (ID)
) ENGINE = INNODB;

CREATE TABLE USER_SEQUENCE (
	SEQ_NAME VARCHAR(50) NOT NULL, 
	SEQ_COUNT BIGINT NOT NULL, 
	PRIMARY KEY (SEQ_NAME)
) ENGINE = INNODB;

-- role uses a sequence in table user_sequence
CREATE TABLE ROLE (
	ID BIGINT NOT NULL, 
	EMAIL VARCHAR(255) NOT NULL, -- not unique, since user can have many roles. this col is here for jee security only! 
	ROLE VARCHAR(255) NOT NULL, 
	USER_ID BIGINT, 
	PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE = INNODB;

CREATE INDEX IDX_ROLE_EMAIL ON ROLE(EMAIL);

-- ---------------------------------------------------------------
-- RULE ENGINE
-- ---------------------------------------------------------------

CREATE TABLE RULE (
	ID BIGINT NOT NULL, 
	NAME VARCHAR(255) NOT NULL, 
	EXPRESSION VARCHAR(2048) NOT NULL, 
	OUTCOME VARCHAR(255) NOT NULL, 
	PRIORITY INT NOT NULL, 
	NAMESPACE VARCHAR(255) NOT NULL, 
	DESCRIPTION VARCHAR(4096) NOT NULL, 
	PRIMARY KEY (ID)
) ENGINE = INNODB;

CREATE TABLE RULE_SEQUENCE (
	SEQ_NAME VARCHAR(50) NOT NULL, 
	SEQ_COUNT BIGINT NOT NULL, 
	PRIMARY KEY (SEQ_NAME)
) ENGINE = INNODB;

-- ---------------------------------------------------------------
-- eEvents.com tables
-- ---------------------------------------------------------------

-- which users have rated an event?
CREATE TABLE EVENT (
	UID VARCHAR(255) NOT NULL, 
	NAME VARCHAR(255) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	THE_TIME DATETIME NOT NULL,
	TEASER_PRICE_CHF DECIMAL(7,2) NOT NULL,
	DESCRIPTION VARCHAR(2048) NOT NULL,
	BOOKING_SYSTEMS VARCHAR(2048) NOT NULL,
	IS_TEASER BOOLEAN NOT NULL,
	IMG_NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (UID)
) ENGINE = INNODB;

-- which users have rated an event?
CREATE TABLE RATING_USER_MAPPING (
	ID BIGINT NOT NULL, 
	EVENT_UID VARCHAR(255) NOT NULL, 
	USER_ID BIGINT NOT NULL, 
	RATING INT NOT NULL, -- what rating did this user give? 
	PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID),
	FOREIGN KEY (EVENT_UID) REFERENCES EVENT(UID)
) ENGINE = INNODB;

CREATE INDEX IDX_RUM_EVENT ON RATING_USER_MAPPING(EVENT_UID);
CREATE INDEX IDX_RUM_USER ON RATING_USER_MAPPING(USER_ID);

-- table of average ratings
CREATE TABLE RATING (
	EVENT_UID VARCHAR(255) NOT NULL, 
	SUM_RATINGS BIGINT NOT NULL, 
	NUM_RATINGS INT NOT NULL, 
	PRIMARY KEY (EVENT_UID),
	FOREIGN KEY (EVENT_UID) REFERENCES EVENT(UID)
) ENGINE = INNODB;

CREATE INDEX IDX_RATING_EVENT ON RATING(EVENT_UID);

-- table of comments
CREATE TABLE COMMENT (
	ID BIGINT NOT NULL, 
	EVENT_UID VARCHAR(255) NOT NULL, 
	COMMENT VARCHAR(2048) NOT NULL,
	USER_ID BIGINT NOT NULL,
	THE_TIME DATETIME NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (EVENT_UID) REFERENCES EVENT(UID),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE = INNODB;

CREATE INDEX IDX_COMMENT_EVENT ON COMMENT(EVENT_UID);
CREATE INDEX IDX_COMMENT_USER ON COMMENT(USER_ID);

-- table of orders
CREATE TABLE ORDERS (
	ID BIGINT NOT NULL, 
	UUID VARCHAR(255) NOT NULL, 
	USER_ID BIGINT NOT NULL,
	THE_TIME DATETIME NOT NULL,
	STATE VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE = INNODB;

CREATE INDEX IDX_ORDER_UUID ON ORDERS(UUID);
CREATE INDEX IDX_ORDER_USERID ON ORDERS(USER_ID);

-- table of order items
-- yes, I know these are not normalised! but i dont care in this instance - the requirement is that i make a copy of the data which will be stored for 10 years.
CREATE TABLE ORDER_ITEM (
	ID BIGINT NOT NULL, 
	ORDER_ID BIGINT NOT NULL, 
	TARIF_NAME VARCHAR(255) NOT NULL,
	TARIF_DESCRIPTION VARCHAR(255) NOT NULL,
	TARIF_CONDITIONS VARCHAR(2048) NOT NULL,
	TARIF_QTY SMALLINT NOT NULL, 
	TARIF_PRICE_CHF DECIMAL(7,2) NOT NULL, 
	BOOKING_REF VARCHAR(255) NOT NULL, 
	EVENT_UID VARCHAR(255) NOT NULL,
	EVENT_NAME VARCHAR(255) NOT NULL,
	EVENT_DATE DATETIME NOT NULL,
	BOOKING_SYSTEM_CODE VARCHAR(20) NOT NULL,
	PARTNER_REFERENCE VARCHAR(255) NOT NULL,
	STATE VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID) 
	-- FOREIGN KEY (EVENT_UID) REFERENCES EVENT(UID) -> not wanted, because otherwise we can never ever clean up events!
) ENGINE = INNODB;

CREATE INDEX IDX_ORDERITEM_BOOKINGREF ON ORDER_ITEM(BOOKING_REF);
CREATE INDEX IDX_ORDERITEM_EVENTUID ON ORDER_ITEM(EVENT_UID);
CREATE INDEX IDX_ORDERITEM_ORDERID ON ORDER_ITEM(ORDER_ID); -- this is really important!

-- table of accounts
CREATE TABLE ACCOUNT_ENTRY (
	ID BIGINT NOT NULL,
	EVENT_ID INT NOT NULL, 
	BOOKING_SYSTEM_CODE VARCHAR(20) NOT NULL,
	TARIF_NAME VARCHAR(255) NOT NULL, 
	TARIF_PRICE_CHF DECIMAL(7,2) NOT NULL, 
	REFERENCE_NUMBER VARCHAR(255) UNIQUE,
	PARTNER_REFERENCE VARCHAR(255) UNIQUE,
	STATE VARCHAR(25) NOT NULL,
	CREATED DATETIME NOT NULL,
	LAST_UPDATED DATETIME NOT NULL,
	PRIMARY KEY (ID)
	-- FK on event missing - this is auditing info and will outlive the event!
) ENGINE = INNODB;

CREATE INDEX IDX_ACCOUNTENTRY_REFERENCENUMBER ON ACCOUNT_ENTRY(REFERENCE_NUMBER);
CREATE INDEX IDX_ACCOUNTENTRY_PARTNERREFERENCE ON ACCOUNT_ENTRY(PARTNER_REFERENCE);

-- table of payments
CREATE TABLE PAYMENT (
	ID BIGINT NOT NULL, 
	ORDER_UUID VARCHAR(255) NOT NULL,
	PRICE_CHF DECIMAL(7,2) NOT NULL, 
	TOKEN_1 VARCHAR(255), -- the one we send to the partner, which they generated for us
	TOKEN_2 VARCHAR(255), -- the one we get when the user returns to our site
	STATE VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = INNODB;

CREATE INDEX IDX_PAYMENT_ORDER ON PAYMENT(ORDER_UUID);

-- sequences for all tables specific to this eevents app
CREATE TABLE EVENTS_SEQUENCES (
	SEQ_NAME VARCHAR(50) NOT NULL, 
	SEQ_COUNT BIGINT NOT NULL, 
	PRIMARY KEY (SEQ_NAME)
) ENGINE = INNODB;

-- table of configuration data
CREATE TABLE CONFIG (
	ID VARCHAR(255) NOT NULL,
	VAL VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = INNODB;

-- table of session cache
CREATE TABLE SESSION_CACHE (
	ID VARCHAR(255) NOT NULL,
	VAL LONGBLOB NOT NULL,
	LAST_USED DATETIME NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = INNODB;

-- -----------------------------
-- views
-- -----------------------------

CREATE VIEW BOOKINGS AS 
SELECT 
	U.NAME, 
	OI.BOOKING_REF, 
	OI.TARIF_NAME, 
	OI.TARIF_PRICE_CHF, 
	OI.TARIF_QTY,
	OI.STATE, 
	OI.EVENT_UID
FROM 
	ORDER_ITEM OI, 
	ORDERS O, 
	USER U 
WHERE 
	O.ID = OI.ORDER_ID 
	AND O.USER_ID  = U.ID
;
